name: menoreh_library
description: Menoreh library is an open source developed by Panemu Solusi Industri.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # packages local
  form_inputs:
    path: packages/form_inputs/
  domain:
    path: packages/domain/
  data:
    path: packages/data/

  # ui packages
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  dropdown_search: ^5.0.3
  flutter_smart_dialog: ^4.6.2+1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  flutter_launcher_icons: ^0.10.0
  google_fonts: ^3.0.1
  currency_text_input_formatter: ^2.1.8
  dotted_border: ^2.0.0+3
  textfield_tags: ^2.0.2
  photo_view: ^0.14.0
  get: ^4.6.5
  # state management
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  # dependency injection
  get_it: ^7.2.0
  # internationalization & localization
  intl: ^0.17.0
  # handle path # for web
  url_strategy: ^0.2.0
  # functional programming
  dartz: ^0.10.1
  # handle route
  auto_route: ^5.0.2
  # file picker
  desktop_drop: ^0.3.3
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  # table view
  syncfusion_flutter_datagrid: ^20.3.57
  syncfusion_localizations: ^20.3.57
  # chart line
  fl_chart: ^0.55.2
  # package versioning
  package_info_plus: ^3.0.2
  # form validation
  formz: ^0.4.1
  # equality comparisons
  equatable: ^2.0.5
  # flavor environment
  flutter_flavorizr: ^2.1.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/common/

# For update your flavors
# f pub run flutter_flavorizr -p <processor1>,<processor2>
# https://pub.dev/packages/flutter_flavorizr#default-processors-set

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:
  ide: "vscode"

  flavors:
    development:
      app:
        name: "Menoreh Dev"

      android:
        applicationId: "com.biscuit.menoreh_library"
      ios:
        bundleId: "com.biscuit.menoreh_library"

    production:
      app:
        name: "Menoreh Library"

      android:
        applicationId: "com.panemu.menoreh_library"
      ios:
        bundleId: "com.panemu.menoreh_library"