name: form_inputs
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  formz: ^0.4.1

dev_dependencies:
  flutter_lints: ^2.0.0